apiVersion: v1
kind: Secret
metadata:
  name: cloudfront-signer-secrets
  namespace: default
type: Opaque
data:
  KEY_PAIR_ID: S0VZX1BBSVJfSUQ=
  PRIVATE_KEY_SECRET_ID: UFJJVkFURV9LRVlfU0VDUkVUX0lE
  CLOUDFRONT_DOMAIN: Q0xPVURGUk9OVF9ET01BSU4=